USE DATABASE RETAIL_DB;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE ORDERS_RAW (
    ORDER_ID STRING,
    CUSTOMER_ID STRING,
    ORDER_STATUS STRING,
    ORDER_PURCHASE_TIMESTAMP STRING
);

CREATE OR REPLACE TABLE CUSTOMERS_RAW (
    CUSTOMER_ID STRING,
    CUSTOMER_CITY STRING,
    CUSTOMER_STATE STRING
);

CREATE OR REPLACE TABLE PRODUCTS_RAW (
    PRODUCT_ID STRING,
    PRODUCT_CATEGORY_NAME STRING
);